// Renders the repo's markdown into a SQL file for `wrangler d1 execute`.
//
// This is the bulk-seed path: it pushes every post in the repo at once, and needs
// no public write surface on the deployment (see site/README.md → "The publishing
// model"). The agent's publish tool writes a single post over the D1 REST API
// instead; both use postFromMarkdown, so the two paths cannot drift.
//
//   npm run seed:sql
//   npx wrangler d1 execute agenttest-posts --remote --file=seed.sql
//
// Rerunnable: every statement upserts, so running it twice is not a duplicate.

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { postFromMarkdown } from '../src/post-from-file.ts';

const REPO_ROOT = resolve(import.meta.dirname, '../..');
const OUTPUT = resolve(import.meta.dirname, '../seed.sql');

const includeDrafts = process.argv.includes('--drafts') || process.env.SEED_DRAFTS === '1';
const SOURCES = [
  { dir: join(REPO_ROOT, 'posts'), label: 'published' },
  ...(includeDrafts ? [{ dir: join(REPO_ROOT, 'drafts'), label: 'draft' }] : []),
];

/** SQL string literal. The only escaping in the file, kept in one place. */
function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

async function main(): Promise<void> {
  const statements: string[] = [
    '-- Generated by scripts/export-sql.ts. Do not edit by hand.',
    '-- Apply with: npx wrangler d1 execute agenttest-posts --remote --file=seed.sql',
  ];
  const today = new Date().toISOString().slice(0, 10);
  let count = 0;

  if (!includeDrafts) {
    console.log('exporting posts/ only (pass --drafts to include drafts/)');
  }

  for (const source of SOURCES) {
    let files: string[];
    try {
      files = (await readdir(source.dir)).filter((file) => file.endsWith('.md'));
    } catch {
      console.log(`skip ${source.label}: no ${source.dir}`);
      continue;
    }

    for (const file of files.sort()) {
      const post = postFromMarkdown(file, await readFile(join(source.dir, file), 'utf8'), {
        today,
      });

      statements.push(
        [
          `INSERT INTO posts (slug, title, description, published_at, updated_at, body_md, body_html, word_count, approved_quote, sources)`,
          `VALUES (${q(post.slug)}, ${q(post.title)}, ${q(post.description)}, ${q(post.published_at)}, NULL, ${q(post.body_md)}, ${q(post.body_html)}, ${post.word_count}, NULL, NULL)`,
          `ON CONFLICT(slug) DO UPDATE SET`,
          `  title = excluded.title,`,
          `  description = excluded.description,`,
          `  published_at = excluded.published_at,`,
          `  updated_at = datetime('now'),`,
          `  body_md = excluded.body_md,`,
          `  body_html = excluded.body_html,`,
          `  word_count = excluded.word_count;`,
          // Tags are replaced rather than merged, so a tag removed from the
          // frontmatter actually disappears instead of lingering.
          `DELETE FROM post_tags WHERE slug = ${q(post.slug)};`,
          ...post.tags.map(
            (tag) =>
              `INSERT OR IGNORE INTO post_tags (slug, tag) VALUES (${q(post.slug)}, ${q(tag)});`,
          ),
        ].join('\n'),
      );
      count++;
      console.log(`  ${source.label}/${file} -> ${post.slug} (${post.tags.length} tags)`);
    }
  }

  await writeFile(OUTPUT, `${statements.join('\n\n')}\n`);
  console.log(`\n${count} post(s) written to site/seed.sql`);
}

await main();
