// Renders the repo's markdown into a SQL file for `wrangler d1 execute`.
//
// This is how content reaches production. The public Worker has no write surface
// by design (see site/README.md → "The publishing model"), so seeding a deployed
// blog cannot go over HTTP — and `wrangler d1 execute --file` needs no public
// endpoint, no token, and no temporary weakening of the production posture.
//
//   npm run seed:sql
//   npx wrangler d1 execute agenttest-posts --remote --file=seed.sql
//
// Rerunnable: every statement upserts, so running it twice is not a duplicate.
// It shares the rendering pipeline with the Worker, so a post seeded this way is
// byte-identical to one published through the API.

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import {
  deriveDescription,
  deriveTitle,
  parseFrontmatter,
  parseTags,
  slugFromFilename,
} from '../src/frontmatter.ts';
import { countWords, renderMarkdown } from '../src/markdown.ts';

const REPO_ROOT = resolve(import.meta.dirname, '../..');
const OUTPUT = resolve(import.meta.dirname, '../seed.sql');

const includeDrafts = process.argv.includes('--drafts') || process.env.SEED_DRAFTS === '1';
const SOURCES = [
  { dir: join(REPO_ROOT, 'posts'), label: 'published' },
  ...(includeDrafts ? [{ dir: join(REPO_ROOT, 'drafts'), label: 'draft' }] : []),
];

/** SQL string literal. The only escaping in the file, kept in one place. */
function q(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function statementFor(post: {
  slug: string;
  title: string;
  description: string;
  published_at: string;
  body_md: string;
  tags: string[];
}): string {
  const body_html = renderMarkdown(post.body_md);
  const word_count = countWords(post.body_md);

  const lines = [
    `INSERT INTO posts (slug, title, description, published_at, updated_at, body_md, body_html, word_count, approved_quote, sources)`,
    `VALUES (${q(post.slug)}, ${q(post.title)}, ${q(post.description)}, ${q(post.published_at)}, NULL, ${q(post.body_md)}, ${q(body_html)}, ${word_count}, NULL, NULL)`,
    `ON CONFLICT(slug) DO UPDATE SET`,
    `  title = excluded.title,`,
    `  description = excluded.description,`,
    `  published_at = excluded.published_at,`,
    `  updated_at = datetime('now'),`,
    `  body_md = excluded.body_md,`,
    `  body_html = excluded.body_html,`,
    `  word_count = excluded.word_count;`,
    // Tags are replaced rather than merged, so a tag removed from the frontmatter
    // actually disappears instead of lingering.
    `DELETE FROM post_tags WHERE slug = ${q(post.slug)};`,
  ];

  for (const tag of post.tags) {
    lines.push(
      `INSERT OR IGNORE INTO post_tags (slug, tag) VALUES (${q(post.slug)}, ${q(tag)});`,
    );
  }

  return lines.join('\n');
}

async function main(): Promise<void> {
  const statements: string[] = [
    '-- Generated by scripts/export-sql.ts. Do not edit by hand.',
    '-- Apply with: npx wrangler d1 execute agenttest-posts --remote --file=seed.sql',
  ];
  let count = 0;

  if (!includeDrafts) {
    console.log('exporting posts/ only (pass --drafts to include drafts/)');
  }

  for (const source of SOURCES) {
    let files: string[];
    try {
      files = (await readdir(source.dir)).filter((file) => file.endsWith('.md'));
    } catch {
      console.log(`skip ${source.label}: no ${source.dir}`);
      continue;
    }

    for (const file of files.sort()) {
      const raw = await readFile(join(source.dir, file), 'utf8');
      const { fields, body } = parseFrontmatter(raw);
      const slug = slugFromFilename(file);

      statements.push(statementFor({
        slug,
        title: fields.title ?? deriveTitle(body, slug),
        description: fields.description ?? deriveDescription(body),
        published_at: fields.date ?? new Date().toISOString().slice(0, 10),
        body_md: body,
        tags: parseTags(fields.tags),
      }));
      count++;
      console.log(`  ${source.label}/${file} -> ${slug}`);
    }
  }

  await writeFile(OUTPUT, `${statements.join('\n\n')}\n`);
  console.log(`\n${count} post(s) written to site/seed.sql`);
}

await main();
